version: '3.4'

volumes:
  redis_data:
    driver: local

networks:
  starlink:
    driver: bridge

services:
  rocketdev.dev:
    hostname: rocketdev.dev
    container_name: rocketdev.dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/app/src'
    ports:
      - '5000:5000'
    networks:
      - starlink
